Repository PaystackHQ/paystack-android, pull requests merged in 2021-06, with the labels that each got.

#131 Jacoco and Test updates
  example/build.gradle
  example/src/main/resources/jacoco-agent.properties
  paystack/build.gradle
  paystack/src/test/java/co/paystack/android/CardTest.java
  paystack/src/test/java/co/paystack/android/PaystackSdkTest.java
Labels: CI, enhancement

#127 Feat/transaction manager testing
  .github/workflows/SonarCloud.yml
  build.gradle
  paystack/build.gradle
  paystack/src/debug/AndroidManifest.xml
  paystack/src/debug/java/co/paystack/android/TestActivity.kt
  paystack/src/test/java/co/paystack/android/TransactionManagerTest.kt
Labels: enhancement

#135 Fixes an issue where Jacoco test coverage doesn't get generated.
  .github/workflows/SonarCloud.yml
  example/build.gradle
  paystack/build.gradle
Labels: CI, bug

#134 Adds layer to access data from paystack-api
  paystack/build.gradle
  paystack/src/main/java/co/paystack/android/api/ApiCallback.kt
  paystack/src/main/java/co/paystack/android/api/ChargeApiCallback.kt
  paystack/src/main/java/co/paystack/android/api/PaystackRepository.kt
  paystack/src/main/java/co/paystack/android/api/PaystackRepositoryImpl.kt
  paystack/src/main/java/co/paystack/android/api/model/ChargeResponse.kt
  paystack/src/main/java/co/paystack/android/api/model/TransactionInitResponse.kt
  paystack/src/main/java/co/paystack/android/api/request/ChargeParams.kt
  paystack/src/main/java/co/paystack/android/api/request/TransactionInitRequestBody.kt
  paystack/src/main/java/co/paystack/android/api/request/ValidateTransactionParams.kt
  paystack/src/main/java/co/paystack/android/api/service/PaystackApiService.kt
  paystack/src/main/java/co/paystack/android/api/service/converter/NoWrap.kt
  paystack/src/main/java/co/paystack/android/api/utils/MapExt.kt
  paystack/src/test/java/co/paystack/android/api/FakeCall.kt
  paystack/src/test/java/co/paystack/android/api/PaystackRepositoryImplTest.kt
Labels: enhancement
