Repository PaystackHQ/paystack-android, pull requests merged in 2021-05, with the labels that each got.

#122 Upgrade Kotlin (1.4.30) and Coroutines (1.4.2)
  build.gradle
  paystack/build.gradle
Labels: Chore

#123 Update SonarCloud.yml
  .github/workflows/SonarCloud.yml
Labels: CI, Chore

#124 Inject TransactionManager and its dependencies
  paystack/src/main/java/co/paystack/android/Factory.kt
  paystack/src/main/java/co/paystack/android/Paystack.java
  paystack/src/main/java/co/paystack/android/PaystackSdkComponent.kt
  paystack/src/main/java/co/paystack/android/TransactionManager.java
  paystack/src/main/java/co/paystack/android/api/ApiClient.java
  paystack/src/main/java/co/paystack/android/api/di/ApiComponent.kt
  paystack/src/main/java/co/paystack/android/ui/AuthActivity.java
Labels: enhancement

#125 Pass Device ID to BaseRequestBody via a constructor call.
  paystack/src/main/java/co/paystack/android/TransactionManager.java
  paystack/src/main/java/co/paystack/android/api/request/BaseRequestBody.java
  paystack/src/main/java/co/paystack/android/api/request/ChargeRequestBody.java
  paystack/src/main/java/co/paystack/android/api/request/ValidateRequestBody.java
Labels: Chore, enhancement

#126 Update gradle wrapper to 6.7.1
  gradle/wrapper/gradle-wrapper.properties
Labels: Chore, skip-changelog

#128 Run testDebug builds in place of test in CI
  .github/workflows/SonarCloud.yml
Labels: CI, enhancement
